#!/bin/bash
#
# shellUnity (Shell Script)
# 
# Objetivo: Framework de testes unitários para Shell Script.
# 
# Site: https://dirack.github.io
# 
# Versão 1.0
# 
# Programador:  Rodolfo A C Neves (Dirack) 30/10/2020
# 
# Email: rodolfo_profissional@hotmail.com
# 
# Licença: .

trap RESULT_UNITY exit

NUMBER_OF_TESTS_UNITY="0"
NUMBER_OF_FAILURES_UNITY="0"
NUMBER_OF_IGNORED_UNITY="0"
FINISHED_ALL_TESTS_UNITY="0"

RESULT_UNITY(){
	
	FINISHED_ALL_TESTS_UNITY="1"
	echo -e "\n-----------------------"
	echo "$NUMBER_OF_TESTS_UNITY Tests $NUMBER_OF_FAILURES_UNITY Failures $NUMBER_OF_IGNORED_UNITY Ignored"
	[ "$NUMBER_OF_FAILURES_UNITY" -eq "0" ] && TEST 0 && exit 0
	TEST 1 && exit 1
}

TEST(){

	NUMBER_OF_TESTS_UNITY=$((NUMBER_OF_TESTS_UNITY+1))

	if [ "$FINISHED_ALL_TESTS_UNITY" == "0" ]
	then
		echo -n "$0:num:teste:"
	fi

	if [ "$1" == "0" ] 
	then
		echo -e "\033[42mPASS\033[m"
	else
		NUMBER_OF_FAILURES_UNITY=$((NUMBER_OF_FAILURES_UNITY+1))
		echo -e "\033[41mFAIL\033[m"
	fi
	
}

TEST_FAIL(){
	return 1
}

TEST_FAIL_MESSAGE(){

	echo "$1"
	return 1
}

TEST_PASS(){

	return 0
}

TEST_PASS_MESSAGE(){

	echo "$1"
	return 0

}

TEST_MESSAGE(){
	echo "INFO: $1"
}

TEST_ASSERT_EQUAL(){

	CONDITION=$(echo "$1==$2" | bc -l)
       	[ "$CONDITION" == "1" ] && TEST 0 && return 0
	TEST 1 && return 1
}

TEST_ASSERT_NOT_EQUAL(){

	CONDITION=$(echo "$1!=$2" | bc -l)
        [ "$CONDITION" == "1" ]	&& return 0
	return 1
}

TEST_ASSERT_TRUE(){

	CONDITION=$(echo "$1" | bc -l)
	[ "$CONDITION" == "1" ] && return 0
	return 1
}

TEST_ASSERT_FALSE(){

	CONDITION=$(echo "$1" | bc -l)
	[ "$CONDITION" == "0" ] && return 0
	return 1
}

TEST_ASSERT_EQUAL_STRING(){

	[ "$1" == "$2" ] && return 0
	return 1
}
