#!/bin/bash
#
# shellunity (Shell Script)
# 
# Objetivo: Framework de testes unitários para Shell Script.
# 
# Site: https://www.geofisicando.com
# 
# Programador: Rodolfo A C Neves (Dirack) 30/10/2020
# 
# Email: rodolfo_profissional@hotmail.com
# 
# Licença: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.

trap RESULT_UNITY exit

NUMBER_OF_TESTS_UNITY="0"
NUMBER_OF_FAILURES_UNITY="0"
NUMBER_OF_IGNORED_UNITY="0"
FINISHED_ALL_TESTS_UNITY="0"
TEST_IGNORE_UNITY="0"

for PARAM in "$@"
do
	case "$PARAM" in

		-c | --color)
			YELLOW="\033[43m"
			GREEN="\033[42m"
			RED="\033[41m"
			END="\033[m"
		;;

		-v | --verbose)
			VERBOSE="1"
		;;

		*)
			YELLOW=""
			GREEN=""
			RED=""
			END=""
		;;

	esac
done	

RESULT_UNITY(){
	
	FINISHED_ALL_TESTS_UNITY="1"
	echo -e "\n-----------------------"
	echo "$NUMBER_OF_TESTS_UNITY Tests $NUMBER_OF_FAILURES_UNITY Failures $NUMBER_OF_IGNORED_UNITY Ignored"
	[ "$NUMBER_OF_FAILURES_UNITY" -eq "0" ] && TEST_UNITY 0 && exit 0
	TEST_UNITY 1 && exit 1
}

TEST_UNITY(){

	NUMBER_OF_TESTS_UNITY=$((NUMBER_OF_TESTS_UNITY+1))
	[ "$TEST_IGNORE_UNITY" == "1" ] && {
		NUMBER_OF_IGNORED_UNITY=$((NUMBER_OF_IGNORED_UNITY+1))
		echo -e "$0:$2:$3:${YELLOW}IGNORED${END}"
		return
	}

	if [ "$FINISHED_ALL_TESTS_UNITY" == "0" ]
	then
		echo -n "$0:$2:$3:"
	fi

	if [ "$1" == "0" ] 
	then
		echo -e "${GREEN}PASS${END}"
	else
		NUMBER_OF_FAILURES_UNITY=$((NUMBER_OF_FAILURES_UNITY+1))
		if [ "$VERBOSE" == "1" ]
		then
			MSG="$4"
			if [ -n "$4" ]
			then
				MSG=": $MSG"
			fi
			echo -e "${RED}FAIL${END}$MSG"
		else
			echo -e "${RED}FAIL${END}"
		fi

	fi
	
}

TEST_IGNORE(){
	if [ "$1" == "on" ]
	then
		TEST_IGNORE_UNITY="1"
	elif [ "$1" == "off" ]
	then
		TEST_IGNORE_UNITY="0"
	fi
}

TEST_MESSAGE(){

	echo "$0:$BASH_LINENO:INFO: $1"
}

TEST_FAIL(){
	TEST_UNITY 1 "$BASH_LINENO" "$FUNCNAME"
}

TEST_FAIL_MESSAGE(){
	
	echo "$0:$BASH_LINENO:FAIL: $1"
	TEST_UNITY 1 "$BASH_LINENO" "$FUNCNAME"
}

TEST_PASS(){

	TEST_UNITY 0 "$BASH_LINENO" "$FUNCNAME"
}

TEST_PASS_MESSAGE(){

	echo "$0:$BASH_LINENO:PASS: $1"
	TEST_UNITY 0 "$BASH_LINENO" "$FUNCNAME"

}


TEST_ASSERT_EQUAL(){

	CONDITION=$(echo "$1==$2" | bc -l)
       	[ "$CONDITION" == "1" ] && TEST_UNITY 0 "$BASH_LINENO" "$FUNCNAME" ||
			TEST_UNITY 1 "$BASH_LINENO" "$FUNCNAME" "Expected $1 Was $2"
}

TEST_ASSERT_NOT_EQUAL(){

	CONDITION=$(echo "$1!=$2" | bc -l)
        [ "$CONDITION" == "1" ]	&& TEST_UNITY 0 "$BASH_LINENO" "$FUNCNAME" ||
			TEST_UNITY 1 "$BASH_LINENO" "$FUNCNAME" "Expected $1 not equal $2"
}

TEST_ASSERT_TRUE(){

	CONDITION=$(echo "$1" | bc -l)
	[ "$CONDITION" == "1" ]	&& TEST_UNITY 0 "$BASH_LINENO" "$FUNCNAME" ||
		TEST_UNITY 1 "$BASH_LINENO" "$FUNCNAME" "Expected TRUE Was FALSE"

}

TEST_ASSERT_FALSE(){

	CONDITION=$(echo "$1" | bc -l)
	[ "$CONDITION" == "0" ]	&& TEST_UNITY 0 "$BASH_LINENO" "$FUNCNAME" ||
		TEST_UNITY 1 "$BASH_LINENO" "$FUNCNAME" "Expected FALSE Was TRUE"
}

TEST_ASSERT_EQUAL_STRING(){

	[ "$1" == "$2" ] && TEST_UNITY 0 "$BASH_LINENO" "$FUNCNAME" ||
		TEST_UNITY 1 "$BASH_LINENO" "$FUNCNAME" \
			"Expected $1 Was $2\n$(diff -d -u <( printf '%s\n' "$1" ) <( printf '%s\n' "$2" ) | sed -n '3,$p')"

}

TEST_FILE_FIND(){
	[ -f "$1" ] && TEST_UNITY 0 "$BASH_LINENO" "$FUNCNAME" ||
		TEST_UNITY 1 "$BASH_LINENO" "$FUNCNAME" "File $1 not found"
}

TEST_DIR_FIND(){
	[ -d "$1" ] && TEST_UNITY 0 "$BASH_LINENO" "$FUNCNAME" ||
		TEST_UNITY 1 "$BASH_LINENO" "$FUNCNAME" "Directory $1 not found"
}

TEST_FILE_X(){
	[ -x "$1" ] && TEST_UNITY 0 "$BASH_LINENO" "$FUNCNAME" ||
		TEST_UNITY 1 "$BASH_LINENO" "$FUNCNAME" "Permission X not enabled for $1"
}

TEST_FILE_W(){
	[ -w "$1" ] && TEST_UNITY 0 "$BASH_LINENO" "$FUNCNAME" ||
		TEST_UNITY 1 "$BASH_LINENO" "$FUNCNAME" "Permission W not enabled for $1"
}

TEST_FILE_R(){
	[ -r "$1" ] && TEST_UNITY 0 "$BASH_LINENO" "$FUNCNAME" ||
		TEST_UNITY 1 "$BASH_LINENO" "$FUNCNAME" "Permission R not enabled for $1"
}

TEST_ISATTY(){
	[ -t "$1" ] && TEST_UNITY 0 "$BASH_LINENO" "$FUNCNAME"	||
		TEST_UNITY 1 "$BASH_LINENO" "$FUNCNAME" "$1 is not a TTY"
}

TEST_FILE_NEWER(){
	[ "$1" -nt "$2" ] && TEST_UNITY 0 "$BASH_LINENO" "$FUNCNAME" ||
		TEST_UNITY 1 "$BASH_LINENO" "$FUNCNAME" "Expected $1 newer than $2"
}

TEST_FILE_OLDER(){
	[ "$1" -ot "$2" ] && TEST_UNITY 0 "$BASH_LINENO" "$FUNCNAME" ||
		TEST_UNITY 1 "$BASH_LINENO" "$FUNCNAME" "Expected $1 older than $2"
}

TEST_FILE_EQUAL(){
	[ "$1" -ef "$2" ] && TEST_UNITY 0 "$BASH_LINENO" "$FUNCNAME" ||
		TEST_UNITY 1 "$BASH_LINENO" "$FUNCNAME" "Expected file $1 equal to file $2"
}

TEST_FILE_EMPTY(){
	[ ! -s "$1" ] && TEST_UNITY 0 "$BASH_LINENO" "$FUNCNAME" ||
		TEST_UNITY 1 "$BASH_LINENO" "$FUNCNAME" "Expected file $1 empty"
}
